
name: Cypress E2E with Allure

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Compose and start services
        run: |
          docker-compose up -d --build

      - name: Wait for services to be ready
        run: |
          set -e
          for i in $(seq 1 60); do
            if curl -sSf http://localhost:8001/ >/dev/null 2>&1; then
              echo "Service ready"
              break
            fi
            echo "waiting... ($i)"
            sleep 2
          done

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests (with Allure)
        env:
          CYPRESS_baseUrl: http://localhost:8002
        run: |
          mkdir -p allure-results
          npx cypress run --browser chrome --config video=false --env allure=true

      - name: Generate Allure report
        run: npx allure generate allure-results -o allure-report --clean

      - name: Upload Allure report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ github.run_id }}
          path: ./allure-report

      - name: Comment PR with Allure artifact link
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pr = context.payload.pull_request.number;
            const runId = context.runId;
            const artifactName = `allure-report-${runId}`;
            const runUrl = `https://github.com/${owner}/${repo}/actions/runs/${runId}`;
            const body = `Allure report for this PR was uploaded as an artifact named **${artifactName}**. Download it from the Actions run: ${runUrl} (see the "Artifacts" section).`;
            await github.issues.createComment({ owner, repo, issue_number: pr, body });

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-allure-artifacts
          path: |
            allure-report/**
            allure-results/**
            cypress/screenshots/**
            cypress/videos/**

      - name: Tear down docker-compose
        if: always()
        run: docker-compose down -v
