
name: Cypress E2E with Allure

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  issues: write
  actions: read
  pages: write
  id-token: write
  # change contents to write when deploying via gh-pages
  # (we'll update below before commit)

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Compose and start services
        run: |
          set -e
          # prefer 'docker compose', fall back to 'docker-compose', otherwise install pip docker-compose
          if docker compose version >/dev/null 2>&1; then
            echo "Using 'docker compose'"
            docker compose up -d --build
          elif command -v docker-compose >/dev/null 2>&1; then
            echo "Using 'docker-compose' binary"
            docker-compose up -d --build
          else
            echo "No docker compose found, installing docker-compose via pip"
            python3 -m pip install --user docker-compose
            export PATH="$HOME/.local/bin:$PATH"
            docker-compose up -d --build
          fi

      - name: Wait for services to be ready
        run: |
          set -e
          for i in $(seq 1 60); do
            if curl -sSf http://localhost:8001/ >/dev/null 2>&1; then
              echo "Service ready"
              break
            fi
            echo "waiting... ($i)"
            sleep 2
          done

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests (with Allure)
        env:
          CYPRESS_baseUrl: http://localhost:8002
        run: |
          mkdir -p allure-results
          npx cypress run --browser chrome --config video=false --env allure=true

      - name: Generate Allure report
        run: npx allure generate allure-results -o allure-report --clean

      - name: Install Chromium for headless screenshot
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Screenshot Allure report (preview) using Chromium headless
        run: |
          mkdir -p allure-report
          FILE="file://$(pwd)/allure-report/index.html"
          # generate screenshot; if it fails, continue (we'll still upload artifacts)
          chromium-browser --headless --disable-gpu --screenshot=allure-report/preview.png --window-size=1200,900 "$FILE" || true

      - name: Add deploy info to Allure report
        if: always()
        run: |
          echo "Run ID: $GITHUB_RUN_ID" > allure-report/DEPLOY_INFO.txt || true
          echo "Repository: $GITHUB_REPOSITORY" >> allure-report/DEPLOY_INFO.txt || true
          echo "Run URL: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> allure-report/DEPLOY_INFO.txt || true
          echo "Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> allure-report/DEPLOY_INFO.txt || true

      - name: Show `allure-report` contents (debug)
        if: always()
        run: |
          echo "-- listing allure-report --"
          ls -la ./allure-report || true
          echo "-- head of index.html --"
          head -n 30 ./allure-report/index.html || true
      - name: "Deploy allure-report to gh-pages branch"
        id: deploy_pages
        if: always()
        continue-on-error: true
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          # avoid setting cname; adjust user/email if you want attribution
          keep_files: true
          commit_message: "Deploy Allure report from run ${{ github.run_id }}"

      - name: "Fallback: manual git push to gh-pages if deploy failed"
        if: always() && steps.deploy_pages.outcome != 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Peaceiris deploy failed (or returned non-success). Attempting manual push to gh-pages as fallback."
          set -e
          cd ./allure-report
          git init
          git checkout -b gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "Deploy Allure report from run $GITHUB_RUN_ID" || true
          # push using token; suppress output that may include token
          GIT_PUSH_URL="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push --force "$GIT_PUSH_URL" gh-pages:gh-pages || {
            echo "Manual push failed. Check branch protections or token permissions.";
            exit 1;
          }

      - name: Ensure Pages source is gh-pages and wait for build
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f1)
          REPO=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f2)
          echo "Setting Pages source to gh-pages branch for $OWNER/$REPO"
          # Set the pages source
          curl -s -X PUT \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${OWNER}/${REPO}/pages \
            -d '{"source":{"branch":"gh-pages","path":"/"}}' || true

          # Trigger an immediate Pages build
          echo "Triggering Pages build via API"
          curl -s -X POST \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${OWNER}/${REPO}/pages/builds || true

          # Poll Pages build status
          # ensure jq is available
          sudo apt-get update && sudo apt-get install -y jq || true
          for i in $(seq 1 10); do
            echo "Checking Pages build status (attempt $i) ..."
            api_out=$(curl -s -H "Authorization: Bearer ${GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" https://api.github.com/repos/${OWNER}/${REPO}/pages || true)
            echo "Raw Pages API response:" > /tmp/pages_api.json
            echo "$api_out" >> /tmp/pages_api.json
            cat /tmp/pages_api.json
            status=$(echo "$api_out" | jq -r '.status' || true)
            echo "Pages API status: $status"
            # write API response to job summary for debugging
            echo "--- Pages API response (attempt $i) ---" >> $GITHUB_STEP_SUMMARY || true
            head -c 4096 /tmp/pages_api.json >> $GITHUB_STEP_SUMMARY || true
            if [ "$status" = "built" ] || [ "$status" = "built, cached" ]; then
              echo "Pages build status is: $status"
              break
            fi
            sleep $((i*2))
          done

      - name: Pages smoke-test (retry and report)
        if: always()
        run: |
          OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f1)
          REPO=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f2)
          PAGES_URL="https://${OWNER}.github.io/${REPO}/"
          echo "Checking Pages URL: $PAGES_URL"
          status=0
          body_file=$(mktemp)
          for i in $(seq 1 10); do
            echo "Attempt $i..."
            http_status=$(curl -s -o "$body_file" -w "%{http_code}" "$PAGES_URL" || true)
            echo "HTTP status: $http_status"
            if [ "$http_status" = "200" ]; then
              status=200
              break
            fi
            sleep $((i*2))
          done
          echo "Pages final HTTP status: $status"
          echo "Pages final HTTP status: $status" >> $GITHUB_STEP_SUMMARY || true
          echo "--- response head (first 2KB) ---" >> $GITHUB_STEP_SUMMARY || true
          head -c 2048 "$body_file" >> $GITHUB_STEP_SUMMARY || true
          rm -f "$body_file" || true

      - name: Output Pages info to job summary
        if: always()
        run: |
          OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f1)
          REPO=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f2)
          PAGES_URL="https://${OWNER}.github.io/${REPO}/"
          echo "Deployed Allure report (if push succeeded) to: $PAGES_URL"
          echo "Deployed Allure report (if push succeeded) to: $PAGES_URL" >> $GITHUB_STEP_SUMMARY || true
          echo "Actions run URL: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_STEP_SUMMARY || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-allure-artifacts
          path: |
            allure-report/**
            allure-results/**
            cypress/screenshots/**
            cypress/videos/**

      - name: Tear down docker-compose
        if: always()
        run: |
          set -e
          if docker compose version >/dev/null 2>&1; then
            docker compose down -v
          elif command -v docker-compose >/dev/null 2>&1; then
            docker-compose down -v
          else
            python3 -m pip install --user docker-compose
            export PATH="$HOME/.local/bin:$PATH"
            docker-compose down -v
          fi
