
name: Cypress E2E with Allure

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  issues: write
  actions: read
  pages: write
  id-token: write
  # change contents to write when deploying via gh-pages
  # (we'll update below before commit)

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Compose and start services
        run: |
          set -e
          # prefer 'docker compose', fall back to 'docker-compose', otherwise install pip docker-compose
          if docker compose version >/dev/null 2>&1; then
            echo "Using 'docker compose'"
            docker compose up -d --build
          elif command -v docker-compose >/dev/null 2>&1; then
            echo "Using 'docker-compose' binary"
            docker-compose up -d --build
          else
            echo "No docker compose found, installing docker-compose via pip"
            python3 -m pip install --user docker-compose
            export PATH="$HOME/.local/bin:$PATH"
            docker-compose up -d --build
          fi

      - name: Wait for services to be ready
        run: |
          set -e
          for i in $(seq 1 60); do
            if curl -sSf http://localhost:8001/ >/dev/null 2>&1; then
              echo "Service ready"
              break
            fi
            echo "waiting... ($i)"
            sleep 2
          done

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests (with Allure)
        env:
          CYPRESS_baseUrl: http://localhost:8002
        run: |
          mkdir -p allure-results
          npx cypress run --browser chrome --config video=false --env allure=true

      - name: Generate Allure report
        run: npx allure generate allure-results -o allure-report --clean

      - name: Install Chromium for headless screenshot
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Screenshot Allure report (preview) using Chromium headless
        run: |
          mkdir -p allure-report
          FILE="file://$(pwd)/allure-report/index.html"
          # generate screenshot; if it fails, continue (we'll still upload artifacts)
          chromium-browser --headless --disable-gpu --screenshot=allure-report/preview.png --window-size=1200,900 "$FILE" || true

      - name: Add deploy info to Allure report
        if: always()
        run: |
          echo "Run ID: $GITHUB_RUN_ID" > allure-report/DEPLOY_INFO.txt || true
          echo "Repository: $GITHUB_REPOSITORY" >> allure-report/DEPLOY_INFO.txt || true
          echo "Run URL: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> allure-report/DEPLOY_INFO.txt || true
          echo "Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> allure-report/DEPLOY_INFO.txt || true

      - name: Deploy `allure-report` to gh-pages branch
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          # avoid setting cname; adjust user/email if you want attribution
          keep_files: true
          commit_message: "Deploy Allure report from run ${{ github.run_id }}"

      - name: Output Pages info to job summary
        if: always()
        run: |
          OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f1)
          REPO=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f2)
          PAGES_URL="https://${OWNER}.github.io/${REPO}/"
          echo "Deployed Allure report (if push succeeded) to: $PAGES_URL"
          echo "Deployed Allure report (if push succeeded) to: $PAGES_URL" >> $GITHUB_STEP_SUMMARY || true
          echo "Actions run URL: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_STEP_SUMMARY || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-allure-artifacts
          path: |
            allure-report/**
            allure-results/**
            cypress/screenshots/**
            cypress/videos/**

      - name: Tear down docker-compose
        if: always()
        run: |
          set -e
          if docker compose version >/dev/null 2>&1; then
            docker compose down -v
          elif command -v docker-compose >/dev/null 2>&1; then
            docker-compose down -v
          else
            python3 -m pip install --user docker-compose
            export PATH="$HOME/.local/bin:$PATH"
            docker-compose down -v
          fi
